### ISSUE TITLE
Is it necessary to throw ValueError?

### ISSUE THREAD

**Issue by sstults** [o19s/search-metrics#2]
https://github.com/o19s/search-metrics/blob/6fd2943aee8397d959d11b9b555382779ecaa949/qual.py#L78

In cases where n > len(judgements), can we just set n = len(judgements)?

**Comment by david-fisher** [comment]
All remaining judgments up to position n may be assumed to be 0, irrelevant, with the resultant DCG being correct. So, no, I'd say the ValueError should not be raised.
